### ISSUE TITLE
Bug in add-admin

### ISSUE THREAD

**Issue by dhanushkt** [nithin356/icems#5]
When u create a new admin account name of the previous logged in account will be replaced with the name of the new admin

Here I've created new admin test from nithin account and the name changed to test :

![](https://i.imgur.com/DgqRWu5.jpg)

**Comment by nithin356** [comment]
How to change 😂

**Comment by dhanushkt** [comment]
I'll review the code and try to correct

**Comment by dhanushkt** [comment]
Got the problem u have given echo $username so even form data is stored in the same veriable so change either form post veriable or session veriable

**Comment by nithin356** [comment]
Fixed #5
